name: tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  smoke-ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 55

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake gcc g++ make \
            dieharder util-linux

      - name: Build
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j"$(nproc)"

      - name: Smoke (hex)
        run: |
          ./build/re4_dump | head -c 32 | hexdump -C

      - name: Dieharder quick
        run: |
          ./build/re4_dump | dieharder -a -g 200 -k 2 -Y 1 -m 1 | tee dieharder_ci.txt

      # ----- PractRand (через tarball, з перевіркою і fallback) -----
      - name: Fetch PractRand
        run: |
          set -euxo pipefail
          mkdir -p external
          TMP=/tmp/PractRand.tar.gz

          # спочатку codeload (реальний .tar.gz), далі fallback на archive; з повторами
          curl -fsSL --retry 5 --retry-delay 2 \
            https://codeload.github.com/imneme/PractRand/tar.gz/refs/heads/dev \
            -o "$TMP" || \
          curl -fsSL --retry 5 --retry-delay 2 \
            https://github.com/imneme/PractRand/archive/refs/heads/dev.tar.gz \
            -o "$TMP"

          # валідація — файл існує і це справжній gzip
          test -s "$TMP"
          file "$TMP" | grep -qi 'gzip' || { echo "Not a gzip tarball"; exit 1; }

          # визначаємо кореневу теку в архіві і перейменовуємо у external/PractRand
          ROOT_DIR="$(tar -tzf "$TMP" | head -1 | cut -d/ -f1)"
          tar -xzf "$TMP" -C external
          mv "external/$ROOT_DIR" external/PractRand

      - name: Build PractRand
        run: |
          make -C external/PractRand/build/Linux -j"$(nproc)"

      - name: PractRand 256MB
        run: |
          set +e
          ./build/re4_dump | external/PractRand/build/Linux/RNG_test stdin64 -tf 2 -te 256MB
          exit 0
