name: tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  smoke-ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 35

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deps
        run: |
          sudo apt-get update
          sudo apt-get install -y dieharder build-essential bsdextrautils


      - name: Build
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j

      - name: Smoke (hex)
        run: ./build/re4_dump | head -c 32 | hexdump -C

      - name: Dieharder quick
        run: ./build/re4_dump | dieharder -a -g 200 -k 2 -Y 1 -m 1 | tee dieharder_ci.txt

      # ----- PractRand (без git clone; через actions/checkout) -----
      - name: Fetch PractRand
        uses: actions/checkout@v4
        with:
          repository: imneme/PractRand
          path: PractRand
          fetch-depth: 1
          ref: master

      - name: Build PractRand
        run: make -C PractRand/build/Linux -j2

      - name: PractRand 256MB
        run: ./build/re4_dump | PractRand/build/Linux/RNG_test stdin64 -tf 2 -te 256MB
