name: tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  smoke-ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 55

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake gcc g++ make \
            dieharder util-linux

      - name: Build
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j

      - name: Smoke (hex)
        run: ./build/re4_dump | head -c 32 | hexdump -C

      - name: Dieharder quick
        run: ./build/re4_dump | dieharder -a -g 200 -k 2 -Y 1 -m 1 | tee dieharder_ci.txt

      # ----- PractRand (через tarball, без автентифікації) -----
      - name: Fetch PractRand
        run: |
          set -euxo pipefail
          mkdir -p external
          # codeload віддає справжній tar.gz; у PractRand актуальна гілка 'dev'
          curl -L https://codeload.github.com/imneme/PractRand/tar.gz/refs/heads/dev \
            -o /tmp/PractRand.tar.gz
          test -s /tmp/PractRand.tar.gz
          tar -xzf /tmp/PractRand.tar.gz -C external
          # знайти розпаковану теку PractRand-* і перейменувати в external/PractRand
          PR_DIR=$(tar -tzf /tmp/PractRand.tar.gz | head -1 | cut -d/ -f1)
          mv "external/${PR_DIR}" external/PractRand
      - name: Build PractRand
        run: make -C external/PractRand/build/Linux -j2

      - name: PractRand 256MB
        run: |
          set +e
          ./build/re4_dump | external/PractRand/build/Linux/RNG_test stdin64 -tf 2 -te 256MB
          exit 0
