name: tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  smoke-ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 55

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deps
        shell: bash
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake gcc g++ make \
            dieharder util-linux curl file tar \
            practrand

      - name: Build
        shell: bash
        run: |
          set -euo pipefail
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j"$(nproc)"

      - name: Smoke (hex)
        shell: bash
        run: |
          set -euo pipefail
          ./build/re4_dump | head -c 32 | hexdump -C

      - name: Dieharder quick
        shell: bash
        run: |
          set -euo pipefail
          ./build/re4_dump | dieharder -a -g 200 -k 2 -Y 1 -m 1 | tee dieharder_ci.txt

      # PractRand без клонування/збирання — використовуємо пакет з Ubuntu
      - name: PractRand 256MB
        shell: bash
        run: |
          # не валимо джобу, навіть якщо тест впаде або вичерпає таймаут
          set +e
          ./build/re4_dump | RNG_test stdin64 -tf 2 -te 256MB
          exit 0
