name: tests
on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc dieharder clang-format-15
          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-15 150
          clang-format --version

      - name: Style (clang-format 15)
        run: clang-format --dry-run --Werror $(git ls-files '*.c' '*.h')

      - name: Build
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j

      - name: Smoke
        run: ./build/re4_dump | head -c 64 | hexdump -C
